#!/bin/bash
# Stats
#
# description: Send-Stats to media server

case $1 in
    start)
        /bin/bash /usr/local/bin/sendstats-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/sendstats-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/sendstats-stop.sh
        /bin/bash /usr/local/bin/sendstats-start.sh
    ;;
esac
exit 0
